const add = require('./add')('prep');

add('for', '');
add('from', '');
add('in', '');
add('including', '');
add('inside', '');
add('into', '');
add('like', '');
add('minus', '');
add('near', '');
add('near', '');
add('notwithstanding', '');
add('of', '');
add('off', '');
add('on', '');
add('onto', '');
add('opposite', '');
add('out', '');
add('outside', '');
add('over', '');
add('past', '');
add('plus', '');
add('regarding', '');
add('save', 'except for (someone or something)');
add('since', '');
add('than', '');
add('through', '');
add('till', '');
add('to', '');
add('toward', '');
add('towards', '');
add('under', '');
add('underneath', '');
add('unlike', '');
add('until', '');
add('up', '');
add('upon', '');
add('versus', '');
add('via', '');
add('with', '');
add('within', '');
add('without', '');

module.exports = add.export();
